## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE

#GPT# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff = 500
application_types_to_replace = list(application_counts[application_counts < cutoff].index)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts[classification_counts > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff = 1000
classifications_to_replace = list(classification_counts[classification_counts < cutoff].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [12]:
# Split our preprocessed data into features and target arrays
X = application_df.drop(columns=['IS_SUCCESSFUL'])
y = application_df['IS_SUCCESSFUL']
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]
hidden_nodes1 = 80
hidden_nodes2 = 30

# Create the Sequential model
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes1, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [16]:
# Train the model
history = nn.fit(X_train_scaled, y_train, epochs=100, validation_data=(X_test_scaled, y_test))

Epoch 1/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5685 - accuracy: 0.7221 - val_loss: 0.5652 - val_accuracy: 0.7227
Epoch 2/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5542 - accuracy: 0.7282 - val_loss: 0.5617 - val_accuracy: 0.7242
Epoch 3/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7320 - val_loss: 0.5610 - val_accuracy: 0.7252
Epoch 4/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5492 - accuracy: 0.7310 - val_loss: 0.5558 - val_accuracy: 0.7274
Epoch 5/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5483 - accuracy: 0.7317 - val_loss: 0.5580 - val_accuracy: 0.7292
Epoch 6/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5476 - accuracy: 0.7343 - val_loss: 0.5596 - val_accuracy: 0.7258
Epoch 7/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7325 - val_loss: 0.5587 - val_accuracy: 0.7283
Epoch 8/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7338 - val_loss: 0.5565 - val_accuracy: 0.7280
Epoch 9/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5447 - accuracy: 0.7357 - val_loss: 0.5578 - val_accuracy: 0.7238
Epoch 10/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5447 - accuracy: 0.7346 - val_loss: 0.5558 - val_accuracy: 0.7283
Epoch 11/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7340 - val_loss: 0.5605 - val_accuracy: 0.7270
Epoch 12/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7342 - val_loss: 0.5563 - val_accuracy: 0.7278
Epoch 13/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7342 - val_loss: 0.5594 - val_accuracy: 0.7210
Epoch 14/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5430 - accuracy: 0.7356 - val_loss: 0.5588 - val_accuracy: 0.7264
Epoch 15/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5427 - accuracy: 0.7357 - val_loss: 0.5588 - val_accuracy: 0.7229
Epoch 16/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5425 - accuracy: 0.7357 - val_loss: 0.5602 - val_accuracy: 0.7251
Epoch 17/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7361 - val_loss: 0.5569 - val_accuracy: 0.7278
Epoch 18/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7360 - val_loss: 0.5590 - val_accuracy: 0.7264
Epoch 19/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7359 - val_loss: 0.5595 - val_accuracy: 0.7217
Epoch 20/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7368 - val_loss: 0.5564 - val_accuracy: 0.7268
Epoch 21/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5414 - accuracy: 0.7357 - val_loss: 0.5563 - val_accuracy: 0.7267
Epoch 22/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7369 - val_loss: 0.5579 - val_accuracy: 0.7259
Epoch 23/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7355 - val_loss: 0.5569 - val_accuracy: 0.7257
Epoch 24/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7367 - val_loss: 0.5578 - val_accuracy: 0.7261
Epoch 25/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7367 - val_loss: 0.5616 - val_accuracy: 0.7289
Epoch 26/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5406 - accuracy: 0.7360 - val_loss: 0.5586 - val_accuracy: 0.7276
Epoch 27/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5400 - accuracy: 0.7371 - val_loss: 0.5570 - val_accuracy: 0.7280
Epoch 28/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5402 - accuracy: 0.7378 - val_loss: 0.5586 - val_accuracy: 0.7249
Epoch 29/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7369 - val_loss: 0.5600 - val_accuracy: 0.7264
Epoch 30/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7375 - val_loss: 0.5562 - val_accuracy: 0.7268
Epoch 31/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7370 - val_loss: 0.5610 - val_accuracy: 0.7258
Epoch 32/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5398 - accuracy: 0.7377 - val_loss: 0.5583 - val_accuracy: 0.7287
Epoch 33/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5390 - accuracy: 0.7372 - val_loss: 0.5598 - val_accuracy: 0.7254
Epoch 34/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7372 - val_loss: 0.5598 - val_accuracy: 0.7236
Epoch 35/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7378 - val_loss: 0.5601 - val_accuracy: 0.7277
Epoch 36/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7384 - val_loss: 0.5589 - val_accuracy: 0.7271
Epoch 37/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7371 - val_loss: 0.5587 - val_accuracy: 0.7286
Epoch 38/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7376 - val_loss: 0.5594 - val_accuracy: 0.7229
Epoch 39/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5385 - accuracy: 0.7377 - val_loss: 0.5593 - val_accuracy: 0.7249
Epoch 40/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7384 - val_loss: 0.5578 - val_accuracy: 0.7264
Epoch 41/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7378 - val_loss: 0.5604 - val_accuracy: 0.7259
Epoch 42/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7391 - val_loss: 0.5605 - val_accuracy: 0.7230
Epoch 43/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7371 - val_loss: 0.5603 - val_accuracy: 0.7262
Epoch 44/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7391 - val_loss: 0.5611 - val_accuracy: 0.7252
Epoch 45/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7386 - val_loss: 0.5655 - val_accuracy: 0.7276
Epoch 46/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7374 - val_loss: 0.5602 - val_accuracy: 0.7248
Epoch 47/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7375 - val_loss: 0.5602 - val_accuracy: 0.7277
Epoch 48/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7384 - val_loss: 0.5596 - val_accuracy: 0.7264
Epoch 49/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7397 - val_loss: 0.5613 - val_accuracy: 0.7274
Epoch 50/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7376 - val_loss: 0.5612 - val_accuracy: 0.7276
Epoch 51/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7384 - val_loss: 0.5618 - val_accuracy: 0.7259
Epoch 52/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7388 - val_loss: 0.5601 - val_accuracy: 0.7277
Epoch 53/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7381 - val_loss: 0.5624 - val_accuracy: 0.7273
Epoch 54/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7385 - val_loss: 0.5621 - val_accuracy: 0.7255
Epoch 55/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7377 - val_loss: 0.5613 - val_accuracy: 0.7257
Epoch 56/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7386 - val_loss: 0.5623 - val_accuracy: 0.7268
Epoch 57/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5368 - accuracy: 0.7381 - val_loss: 0.5616 - val_accuracy: 0.7242
Epoch 58/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5368 - accuracy: 0.7395 - val_loss: 0.5610 - val_accuracy: 0.7287
Epoch 59/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7390 - val_loss: 0.5617 - val_accuracy: 0.7274
Epoch 60/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7392 - val_loss: 0.5628 - val_accuracy: 0.7274
Epoch 61/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7395 - val_loss: 0.5605 - val_accuracy: 0.7257
Epoch 62/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7388 - val_loss: 0.5602 - val_accuracy: 0.7280
Epoch 63/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5363 - accuracy: 0.7397 - val_loss: 0.5610 - val_accuracy: 0.7274
Epoch 64/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7387 - val_loss: 0.5626 - val_accuracy: 0.7246
Epoch 65/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7403 - val_loss: 0.5632 - val_accuracy: 0.7233
Epoch 66/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7392 - val_loss: 0.5629 - val_accuracy: 0.7262
Epoch 67/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7388 - val_loss: 0.5629 - val_accuracy: 0.7286
Epoch 68/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5362 - accuracy: 0.7391 - val_loss: 0.5635 - val_accuracy: 0.7278
Epoch 69/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5360 - accuracy: 0.7392 - val_loss: 0.5643 - val_accuracy: 0.7246
Epoch 70/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7387 - val_loss: 0.5619 - val_accuracy: 0.7232
Epoch 71/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7395 - val_loss: 0.5628 - val_accuracy: 0.7270
Epoch 72/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7388 - val_loss: 0.5622 - val_accuracy: 0.7274
Epoch 73/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7384 - val_loss: 0.5644 - val_accuracy: 0.7262
Epoch 74/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5356 - accuracy: 0.7396 - val_loss: 0.5625 - val_accuracy: 0.7268
Epoch 75/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5355 - accuracy: 0.7397 - val_loss: 0.5614 - val_accuracy: 0.7257
Epoch 76/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7397 - val_loss: 0.5640 - val_accuracy: 0.7277
Epoch 77/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7389 - val_loss: 0.5635 - val_accuracy: 0.7276
Epoch 78/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7393 - val_loss: 0.5631 - val_accuracy: 0.7276
Epoch 79/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7394 - val_loss: 0.5635 - val_accuracy: 0.7271
Epoch 80/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5351 - accuracy: 0.7390 - val_loss: 0.5630 - val_accuracy: 0.7267
Epoch 81/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5354 - accuracy: 0.7401 - val_loss: 0.5646 - val_accuracy: 0.7270
Epoch 82/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7398 - val_loss: 0.5652 - val_accuracy: 0.7268
Epoch 83/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7397 - val_loss: 0.5658 - val_accuracy: 0.7270
Epoch 84/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7395 - val_loss: 0.5662 - val_accuracy: 0.7273
Epoch 85/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7396 - val_loss: 0.5651 - val_accuracy: 0.7246
Epoch 86/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5348 - accuracy: 0.7392 - val_loss: 0.5667 - val_accuracy: 0.7242
Epoch 87/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5346 - accuracy: 0.7397 - val_loss: 0.5673 - val_accuracy: 0.7235
Epoch 88/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7397 - val_loss: 0.5648 - val_accuracy: 0.7238
Epoch 89/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7399 - val_loss: 0.5667 - val_accuracy: 0.7239
Epoch 90/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5354 - accuracy: 0.7391 - val_loss: 0.5624 - val_accuracy: 0.7262
Epoch 91/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7395 - val_loss: 0.5687 - val_accuracy: 0.7265
Epoch 92/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7395 - val_loss: 0.5665 - val_accuracy: 0.7268
Epoch 93/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7398 - val_loss: 0.5664 - val_accuracy: 0.7270
Epoch 94/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7396 - val_loss: 0.5647 - val_accuracy: 0.7259
Epoch 95/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7400 - val_loss: 0.5661 - val_accuracy: 0.7281
Epoch 96/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7398 - val_loss: 0.5670 - val_accuracy: 0.7261
Epoch 97/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7394 - val_loss: 0.5646 - val_accuracy: 0.7268
Epoch 98/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5345 - accuracy: 0.7395 - val_loss: 0.5665 - val_accuracy: 0.7267
Epoch 99/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7399 - val_loss: 0.5659 - val_accuracy: 0.7267
Epoch 100/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7400 - val_loss: 0.5675 - val_accuracy: 0.7254

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - loss: 0.5675 - accuracy: 0.7254 - 257ms/epoch - 1ms/step
Loss: 0.5674824118614197, Accuracy: 0.7253644466400146

In [18]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(